### PR TITLE
Added bold font to all new versions

### PR DESCRIPTION
**Pull request by ntogoc**
Added bold font to all new versions to make it easier to find changes in versions

### CODE REVIEW

**Comment by RumstiBumsti** [comment]
Hi,
thanks for your contribution. Did you manually edit the readme-file? I am concerned, that the automatical update function doesnt work any more if i merge your Pull Request.
BR

**Comment by ntogoc** [comment]
No, I made a simple macro in excel. 
I will look into make the changes to the C# code as well

**Comment by ntogoc** [comment]
Should be done in bc46109

**Comment by RumstiBumsti** [comment]
this will only work the first time

**Pull request closed without merging**
